version: "3"
services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=hotelDB
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin
    ports:
      - "3307:3307"
    volumes:
    - /data/mysql
  spring-boot-jpa-app:
      image: spring-boot-jpa-image
      build: .
      depends_on:
      - mysql-docker-container
      ports:
      - "9991:9991"
      volumes:
      - /data/spring-boot-app